#!/usr/bin/with-contenv bash

# default config
if [ ! -f /config/settings.json ]; then
  cp -f /defaults/settings.json /config/settings.json
fi

# custom config
DOWNLOAD_DIR=$(cat /config/settings.json | grep "download-dir\": \"${TRANSMISSION_DOWNLOAD_DIR}")
if [ -z "$DOWNLOAD_DIR" ]; then
  echo "Setting custom download folder ${TRANSMISSION_DOWNLOAD_DIR}."
  sed -i "s+download-dir\": \".*\"+download-dir\": \"${TRANSMISSION_DOWNLOAD_DIR}\"+g" /config/settings.json
fi

INCOMPLETE_DIR=$(cat /config/settings.json | grep "incomplete-dir\": \"${TRANSMISSION_INCOMPLETE_DIR}")
if [ -z "$INCOMPLETE_DIR" ]; then
  echo "Setting custom incomplete folder ${TRANSMISSION_INCOMPLETE_DIR}."
  sed -i "s+incomplete-dir\": \".*\"+incomplete-dir\": \"${TRANSMISSION_INCOMPLETE_DIR}\"+g" /config/settings.json
fi

WATCH_DIR=$(cat /config/settings.json | grep "watch-dir\": \"${TRANSMISSION_WATCH_DIR}")
if [ ! -z "${TRANSMISSION_WATCH_DIR}" ] && [ -z "$WATCH_DIR" ]; then
  echo "Setting custom watch folder ${TRANSMISSION_WATCH_DIR}."
  sed -i "s+watch-dir\": \".*\"+watch-dir\": \"${TRANSMISSION_WATCH_DIR}\"+g" /config/settings.json
  sed -i "s+watch-dir-enabled\": false,+watch-dir-enabled\": true,+g" /config/settings.json
fi

if [ ! -z "$TRANSMISSION_USER" ] && [ ! -z "$TRANSMISSION_PASSWORD" ]; then
  echo "Setting transmission username and password."
  sed -i "s+rpc-authentication-required\": .*,+rpc-authentication-required\": true,+g" /config/settings.json
  sed -i "s+rpc-username\": \".*\"+rpc-username\": \"$TRANSMISSION_USER\"+g" /config/settings.json
  sed -i "s+rpc-password\": \".*\"+rpc-password\": \"$TRANSMISSION_PASSWORD\"+g" /config/settings.json
fi

if [ ! -d "${TRANSMISSION_DOWNLOAD_DIR}" ]; then
  echo "No download folder found, creating download folder ${TRANSMISSION_DOWNLOAD_DIR}."
  mkdir -p "${TRANSMISSION_DOWNLOAD_DIR}"
fi

if [ ! -d "${TRANSMISSION_INCOMPLETE_DIR}" ]; then
  echo "No incomplete download folder found, creating incomplete download folder ${TRANSMISSION_INCOMPLETE_DIR}."
  mkdir -p "${TRANSMISSION_INCOMPLETE_DIR}"
fi

if [ ! -z "$TRANSMISSION_WATCH_DIR" ] && [ ! -d "${TRANSMISSION_WATCH_DIR}" ]; then
  echo "No watch folder found, creating watch folder ${TRANSMISSION_WATCH_DIR}."
  mkdir -p "${TRANSMISSION_WATCH_DIR}"
fi

# permissions
chown abc:abc /downloads
chown -R abc:abc /config

# web ui
case ${TRANSMISSION_WEB_UI} in
  combustion)
    echo "Setting web ui to 'combustion'."
    export TRANSMISSION_WEB_HOME=/etc/transmission/web/combustion-release
    ;;
  kettu)
    echo "Setting web ui to 'kettu'."
    export TRANSMISSION_WEB_HOME=/etc/transmission/web/kettu-master
    ;;
  *)
    ;;
esac
